from typing import Any

from fastapi.testclient import TestClient


def _create_item(client: TestClient, **overrides: Any) -> dict[str, Any]:
    payload: dict[str, Any] = {"name": "Widget", "quantity": 1, **overrides}
    response = client.post("/api/v1/items", json=payload)
    assert response.status_code == 201, response.text
    return response.json()


def test_list_tables(client: TestClient) -> None:
    response = client.get("/api/v1/tables")
    assert response.status_code == 200
    assert response.json() == {"data": ["items", "notes"]}


def test_disallowed_table_is_rejected(client: TestClient) -> None:
    response = client.get("/api/v1/secret_table")
    assert response.status_code == 404
    assert "not allowed" in response.json()["detail"]

    response = client.post("/api/v1/secret_table", json={"name": "x"})
    assert response.status_code == 404


def test_table_metadata(client: TestClient) -> None:
    response = client.get("/api/v1/items/metadata")
    assert response.status_code == 200
    body = response.json()
    assert body["table"] == "items"
    assert body["has_active_column"] is True
    id_column = next(column for column in body["columns"] if column["name"] == "id")
    assert id_column["primary_key"] is True

    response = client.get("/api/v1/notes/metadata")
    assert response.json()["has_active_column"] is False


def test_create_applies_defaults(client: TestClient) -> None:
    record = _create_item(client, name="DefaultsCheck")
    assert record["active"] == 1
    assert record["created_at"] is not None
    assert record["updated_at"] is not None


def test_create_unknown_column_rejected(client: TestClient) -> None:
    response = client.post("/api/v1/items", json={"name": "x", "no_such_column": 1})
    assert response.status_code == 422
    assert "no_such_column" in response.json()["detail"]


def test_create_autogenerated_pk_rejected(client: TestClient) -> None:
    response = client.post("/api/v1/items", json={"id": 999, "name": "x"})
    assert response.status_code == 422


def test_get_one_and_missing_returns_404(client: TestClient) -> None:
    record = _create_item(client, name="GetOne")
    response = client.get(f"/api/v1/items/{record['id']}")
    assert response.status_code == 200
    assert response.json()["name"] == "GetOne"

    response = client.get("/api/v1/items/999999")
    assert response.status_code == 404


def test_text_filter_is_case_insensitive_partial(client: TestClient) -> None:
    _create_item(client, name="FilterAlpha One")
    _create_item(client, name="filteralpha two")
    _create_item(client, name="Unrelated")

    response = client.get("/api/v1/items", params={"name": "filteralpha"})
    assert response.status_code == 200
    names = [row["name"] for row in response.json()["data"]]
    assert len(names) == 2
    assert all("filteralpha" in name.lower() for name in names)


def test_integer_filter_is_exact(client: TestClient) -> None:
    _create_item(client, name="QtyExact", quantity=777)
    response = client.get("/api/v1/items", params={"quantity": 777})
    assert response.status_code == 200
    rows = response.json()["data"]
    assert len(rows) == 1
    assert rows[0]["quantity"] == 777


def test_unknown_filter_column_returns_422(client: TestClient) -> None:
    response = client.get("/api/v1/items", params={"nonexistent": "x"})
    assert response.status_code == 422
    assert "nonexistent" in response.json()["detail"]


def test_page_size_above_max_is_clamped(client: TestClient) -> None:
    response = client.get("/api/v1/items", params={"page_size": 999})
    assert response.status_code == 200
    # MAX_PAGE_SIZE is 50 in the test environment (see conftest.py).
    assert response.json()["pagination"]["page_size"] == 50


def test_put_and_patch_update_fields(client: TestClient) -> None:
    record = _create_item(client, name="Before", quantity=1)
    record_id = record["id"]

    response = client.put(f"/api/v1/items/{record_id}", json={"name": "AfterPut"})
    assert response.status_code == 200
    assert response.json()["name"] == "AfterPut"

    response = client.patch(f"/api/v1/items/{record_id}", json={"quantity": 42})
    assert response.status_code == 200
    body = response.json()
    assert body["quantity"] == 42
    assert body["name"] == "AfterPut"


def test_update_primary_key_rejected(client: TestClient) -> None:
    record = _create_item(client, name="PkGuard")
    response = client.patch(f"/api/v1/items/{record['id']}", json={"id": 12345})
    assert response.status_code == 422


def test_soft_delete_sets_active_zero(client: TestClient) -> None:
    record = _create_item(client, name="ToDelete")
    record_id = record["id"]

    response = client.delete(f"/api/v1/items/{record_id}")
    assert response.status_code == 200
    assert response.json() == {"status": "deleted", "id": record_id}

    # Hidden by default after soft delete...
    assert client.get(f"/api/v1/items/{record_id}").status_code == 404

    # ...but still present with include_inactive=true.
    response = client.get(f"/api/v1/items/{record_id}", params={"include_inactive": "true"})
    assert response.status_code == 200
    assert response.json()["active"] == 0


def test_soft_delete_without_active_column_returns_400(client: TestClient) -> None:
    response = client.post("/api/v1/notes", json={"body": "note"})
    assert response.status_code == 201, response.text
    note_id = response.json()["id"]

    response = client.delete(f"/api/v1/notes/{note_id}")
    assert response.status_code == 400
    assert "active" in response.json()["detail"]

    # The record was not physically deleted.
    assert client.get(f"/api/v1/notes/{note_id}").status_code == 200


def test_soft_delete_missing_record_returns_404(client: TestClient) -> None:
    response = client.delete("/api/v1/items/999999")
    assert response.status_code == 404
